### ISSUE TITLE
Dark mode and light mode

### ISSUE THREAD

**Issue by roughcoding** [tensorwerk/hangar-gui#1]
Current UI is in dark mode, and we felt a necessity of light mode too.

Current Theme:
![Screenshot 2019-08-23 at 10 47 12 PM](https://user-images.githubusercontent.com/16874047/63610846-0c463600-c5f8-11e9-88c3-5a08e056c4b4.png)

Proposed(light) Theme:
![Screenshot 2019-08-23 at 10 46 51 PM](https://user-images.githubusercontent.com/16874047/63610847-0cdecc80-c5f8-11e9-95dd-dc2d9c25ae22.png)

**Comment by Mupati** [comment]
I will implement this feature

**Comment by roughcoding** [comment]
Oh that's great @Mupati. I'll assign this issue to you. I can do a quick review once you're done, let me know. Also feel free to take a look at the existing repo and suggest if there are any changes you think is beneficial.

**Comment by umr55766** [comment]
Hey @Mupati , any update on this ? If you're willing to pass it on, I'll happy to work on this.

**Comment by Mupati** [comment]
@umr55766 I've implemented and submitted a PR already. @roughcoding is yet to review and merge the PR after she requested some changes to be made to the PR I sent. You might want to check #3 and work on it.
